@startuml
'https://plantuml.com/sequence-diagram

title <b>SYSTEM SEQUENCE DIAGRAM\n
autonumber
'hide footbox
actor "Traffic Manager" as MAN

participant ":System" as System

activate MAN
activate System

MAN -> System : starts importing ships
System --> MAN : asks for the file to import
deactivate System
MAN -> System : types the name of the file
activate System
System --> MAN : imports the ships
deactivate System

@enduml