@startuml
'https://plantuml.com/sequence-diagram

autonumber
participant ":IdleDays" as ui
participant ":DatabaseConnection"
activate ui

ui --> ":DatabaseConnection" : executeUpdate();
activate ":DatabaseConnection"
deactivate ":DatabaseConnection"
deactivate ui
@enduml