@startuml
'https://plantuml.com/class-diagram

class CargoManifestsTransportedUI {
}

class CargoManifestsTransportedController{
    +getID()
    +getCargoManifestTransported(String year)
    +getContManifests()
    +getAverage()
    -getAmount()
    -executeSQLQuery(String sql, DatabaseConnection data)
}

CargoManifestsTransportedUI ..> CargoManifestsTransportedController

@enduml